#!/usr/bin/env bash

_psshrun()
{
    case ${COMP_CWORD} in
    1)
        local configfiles
        cur=${COMP_WORDS[COMP_CWORD]}
        local configfiles="$(for x in `find ${psshrun_configpath} -type f -exec basename {} \;`; do echo ${x}; done)"
        COMPREPLY=( $( compgen -W "${configfiles}" -- ${cur} ) )
        ;;
    *)
        COMPREPLY=()
        ;;
    esac
}
complete -F _psshrun psshrun
